### ISSUE TITLE
Pagination Issue: Next/Prev Button Navigation Skips Pages

### ISSUE THREAD

**Issue by PremPrakashCodes** [bryaneaton13/shadcn-next-link-pagination#1]
When using the pagination feature on the page, the following issue is observed:

1. **Next Button:** 
   - Tapping the "Next" button navigates correctly from page 1 to 2 and 3. However, after reaching the last page (page 50), it does not continue correctly. 
   
2. **Prev Button:** 
   - Tapping the "Prev" button navigates from page 49 to 48, but instead of continuing back to page 1, it behaves unexpectedly.

This issue only occurs when using the "Next" and "Prev" buttons. If the `searchParams` are manually changed in the URL, the pagination functions as expected, allowing navigation to all pages without issues.

**Steps to Reproduce:**
1. Open the page with pagination.
2. Click the "Next" button multiple times until reaching the last page.
3. Observe the behavior at the last page.
4. Click the "Prev" button and observe the behavior.

**Expected Behavior:**
- The "Next" button should navigate through pages sequentially, and after reaching the last page, it should not loop or skip.
- The "Prev" button should navigate back sequentially without skipping any pages.

**Actual Behavior:**
- The "Next" button skips to the last page.
- The "Prev" button does not navigate correctly after page 48.

**Additional Information:**
- The issue does not occur when manually adjusting the `searchParams` in the URL.
- Please provide any relevant logs or screenshots if available.

**Comment by bryaneaton13** [comment]
Thanks so much for reporting this!

In my demo application ([at this link](https://shadcn-next-link-pagination.vercel.app/?page=1)) I wasn't able to reproduce what you were talking about. Are you running into something in your own application? Are you able to share more sample code or a reproduction somehow?
After copying the code from the component into your own application, you're able to modify it and maybe put some logs in or use a debugger to see what might be giving the error. Maybe the `useSearchParams` isn't updated right away or there's some kind of server slowness happening that may cause the page not to refresh properly.

Here's a video walkthrough of me trying to reproduce it and it was working as expected. The "Next" button is disabled properly when there are no more pages (50 on my example page)

https://github.com/user-attachments/assets/b9a33b8f-c23b-4114-b24c-9e00251b70f8
